@startuml

package TricycleBLEService <<Rectangle>> {
    class BatteryPercentage {
        Type: READ
        Value: 80 [UINT8]
    }

    class Mileage {
        Type: READ
        Value: 10000 [UINT32]
    }

    class Load {
        Type: READ
        Value: 100 [UINT16]
    }

    class Events {
        Type: NOTIFY
        Value: 5 [UINT8]
    }

    note bottom of Events
       5 = 1 + 4 = 0b0001 + 0b0100 = Front load too heavy & Battery too hot
    end note
}

enum EventTypes {
    0b0001: Front load too heavy
    0b0010: Package loss
    0b0100: Battery too hot
    0b1000: Motor too hot
}

Events::Value ..> EventTypes : "uses"
@enduml